apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server:latest
        volumeMounts:
        - mountPath: /data
          name: minecraft-server-data
        # - mountPath: /data/whitelist.json
        #   name: minecraft-cm
        #   subPath: whitelist.json
        env:
        - name: EULA
          value: "TRUE"
        - name: ONLINE_MODE
          value: "FALSE"
        # - name: ENABLE_WHITELIST
        #   value: "TRUE"
        ports:
        - containerPort: 25565
        resources:
          requests:
            memory: "2000Mi"
            cpu: "2"
          limits:
            memory: "8000Mi"
            cpu: "8"
      volumes:
      - name: minecraft-server-data
        persistentVolumeClaim:
          claimName: minecraft-server-data
      # - name: minecraft-cm
      #   configMap:
      #     name: minecraft-cm
